### ISSUE TITLE
make文件缺失

### ISSUE THREAD

**Issue by matrix-lisp** [chihyang/eopl3_zh#4] opened 2022-09-22 07:46 UTC
想先睹为快，请问能添加上make文件吗

**Comment by chihyang** [comment] 2022-09-22 14:33
See #2 for details. In fact, if the change of scribble is merged into the official repo, we only need **one command** to compile the whole book, thus making a compile script unnecessary. The problem is not about the compile script, but the compile tool.

**Closed as completed by chihyang** 2022-09-22 14:33 UTC
Labels: duplicate, wontfix
